-- 코드를 작성해주세요
SELECT FISH_INFO.ID, A.FISH_NAME, A.LENGTH
FROM FISH_INFO, FISH_NAME_INFO, (
    SELECT FISH_NAME_INFO.FISH_NAME, MAX(FISH_INFO.LENGTH) AS LENGTH
    FROM FISH_INFO, FISH_NAME_INFO
    WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
    GROUP BY FISH_NAME_INFO.FISH_NAME
    ) A
WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
AND FISH_INFO.LENGTH = A.LENGTH
AND FISH_NAME_INFO.FISH_NAME = A.FISH_NAME
ORDER BY FISH_INFO.ID


